# Generated by Django 3.2.8 on 2026-01-10 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0011_zipcode_is_serviceable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorDirectory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("dba", models.CharField(blank=True, max_length=255)),
                ("vendor_type", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("noa_email", models.EmailField(blank=True, max_length=254)),
                ("primary_county", models.CharField(blank=True, max_length=100)),
                ("owning_business_unit", models.CharField(blank=True, max_length=50)),
                ("county_service_map_raw", models.TextField(blank=True)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(default=False)),
                ("availability", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Vendor Directory Entry",
                "verbose_name_plural": "Vendor Directory Entries",
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="VendorCountyService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_services",
                        to="services.county",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_counties",
                        to="services.servicetype",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="county_services",
                        to="directory.vendordirectory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor County Service",
                "verbose_name_plural": "Vendor County Services",
                "unique_together": {("vendor", "county", "service")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteVendor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="directory.vendordirectory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Vendor",
                "verbose_name_plural": "Favorite Vendors",
                "unique_together": {("user", "vendor")},
            },
        ),
    ]
