# Generated by Django 3.2.8 on 2026-01-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendordirectory",
            name="owning_business_unit",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
