# Generated by Django 3.2.8 on 2026-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_zipcode_is_serviceable"),
        ("directory", "0003_vendorreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendordirectory",
            name="funding_sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="directory_vendors",
                to="services.FundingSource",
            ),
        ),
        migrations.AddField(
            model_name="vendordirectory",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
