# Generated by Django 3.2.8 on 2026-01-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_auto_20260115_2101"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorclaimdocument",
            name="file",
        ),
        migrations.AddField(
            model_name="vendorclaimdocument",
            name="link",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
