# Generated by Django 3.2.8 on 2026-01-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("directory", "0004_auto_20260126_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendordirectory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_vendors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
