# Generated by Django 3.2.8 on 2026-01-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_vendordirectory_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendordirectory",
            name="image",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
