# Generated by Django 3.2.8 on 2026-01-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_auto_20260127_2124"),
        ("directory", "0007_alter_vendordirectory_image"),
    ]

    operations = []
