# Generated by Django 3.2.8 on 2026-01-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0008_merge_20260127_2226"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendordirectory",
            name="owner",
        ),
    ]
