# Generated by Django 3.2.8 on 2026-02-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_add_rejected_status_to_vendorreview"),
        ("directory", "0009_remove_vendordirectory_owner"),
    ]

    operations = []
