# Generated by Django 3.2.8 on 2026-03-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0010_merge_20260211_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePayCareRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('services', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('urgent', 'Urgent'), ('needs_assistance', 'Needs Assistance')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('consumer', 'Consumer'), ('social_worker', 'Social Worker')], default='consumer', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('needs_assistance', models.BooleanField(default=False)),
                ('is_private_pay', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_pay_care_requests', to=settings.AUTH_USER_MODEL)),
                ('notified_vendors', models.ManyToManyField(blank=True, related_name='notified_private_pay_requests', to='directory.VendorDirectory')),
                ('selected_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_private_pay_requests', to='directory.vendordirectory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
