# Generated by Django 3.1.4 on 2020-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0003_auto_20201204_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="funding_sources",
            field=models.ManyToManyField(to="services.FundingSource"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="services",
            field=models.ManyToManyField(to="services.ServiceType"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="zip_codes",
            field=models.ManyToManyField(to="services.ZipCode"),
        ),
    ]
