# Generated by Django 3.1.4 on 2020-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_auto_20201216_1651"),
        ("users", "0005_auto_20201216_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerprofile",
            name="funding_sources",
            field=models.ManyToManyField(
                blank=True, to="services.FundingSource"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="services.ServiceType"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="zip_codes",
            field=models.ManyToManyField(blank=True, to="services.ZipCode"),
        ),
    ]
