# Generated by Django 3.1.4 on 2021-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_agencymanageduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
