# Generated by Django 3.1.4 on 2021-01-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
