# Generated by Django 3.1.4 on 2021-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_providerprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
