# Generated by Django 3.1.5 on 2021-02-23 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_userpreferences"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={"verbose_name_plural": "User Preferences"},
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="request_table_columns",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
