# Generated by Django 3.2.8 on 2023-05-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_providerprofile_zip_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_2fa_enabled', models.BooleanField(default=False)),
                ('otp_2fa_enabled', models.BooleanField(default=False)),
                ('otp_code', models.IntegerField(blank=True, null=True)),
                ('otp_expiration', models.DateTimeField(blank=True, null=True)),
                ('qr_base32', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_auth_url', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('last_configured_2fa', models.DateTimeField(blank=True, null=True)),
                ('last_login_2fa', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
