# Generated by Django 3.2.8 on 2023-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_twofactorauthentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauthentication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
