# Generated by Django 3.2.8 on 2024-08-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_twofactorauthentication_disable_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproviderprofile',
            name='all_docs_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='all_docs_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UploadDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('provider_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_docs', to='users.providerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
