# Generated by Django 3.2.8 on 2024-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20240829_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
