# Generated by Django 3.2.8 on 2024-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_county_options'),
        ('users', '0024_alter_uploaddocs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='counties',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.County'),
        ),
    ]
