# Generated by Django 3.1.4 on 2020-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingsource",
            name="service_type",
            field=models.ManyToManyField(to="services.ServiceType"),
        ),
    ]
