# Generated by Django 3.1.4 on 2021-01-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20201218_1859"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetype",
            name="type",
        ),
    ]
