# Generated by Django 3.1.5 on 2021-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_servicetype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
