# Generated by Django 3.2.8 on 2024-05-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210216_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='immediate_notification',
            field=models.BooleanField(default=False),
        ),
    ]
