# Generated by Django 3.2.8 on 2024-09-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20240829_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name']},
        ),
    ]
