# Generated by Django 3.2.8 on 2024-09-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_county_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
    ]
