# Generated by Django 3.2.8 on 2024-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_county_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='is_serviceable',
            field=models.BooleanField(default=True, help_text="Indicates if this zip code is in Duett's service area"),
        ),
    ]
