# Generated by Django 3.1.4 on 2020-12-15 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0004_auto_20201215_2013"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=5)),
                ("state", models.CharField(max_length=30)),
                ("zip", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PatientRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_prior_authorization",
                    models.BooleanField(default=False),
                ),
                (
                    "transportation_required",
                    models.BooleanField(default=False),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Female"), (2, "Male"), (3, "Other")]
                    ),
                ),
                ("pets", models.BooleanField(default=False)),
                ("smoking", models.BooleanField(default=False)),
                ("equipment", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Open"), (2, "Closed")], default=1
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequested",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(20)
                        ]
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        choices=[(1, "Per Week"), (2, "Per Month")]
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        related_name="provider_interests",
                        to="users.ProviderProfile",
                    ),
                ),
                (
                    "matches",
                    models.ManyToManyField(
                        related_name="provider_matches",
                        to="users.ProviderProfile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patientrequest",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.servicetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestNotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patientrequest",
                    ),
                ),
            ],
        ),
    ]
