# Generated by Django 3.1.4 on 2020-12-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20201215_2013"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequested",
            name="matches",
        ),
        migrations.AddField(
            model_name="servicerequested",
            name="match",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="provider_match",
                to="users.providerprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servicerequested",
            name="interests",
            field=models.ManyToManyField(
                related_name="interested_providers", to="users.ProviderProfile"
            ),
        ),
    ]
