# Generated by Django 3.1.4 on 2020-12-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_fundingsource_service_type"),
        ("patients", "0002_auto_20201215_2106"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequested",
            name="funding_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="services.fundingsource",
            ),
        ),
    ]
