# Generated by Django 3.1.4 on 2020-12-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20201216_1553"),
        ("patients", "0003_servicerequested_funding_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequested",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_providers",
                to="users.ProviderProfile",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequested",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="provider_match",
                to="users.providerprofile",
            ),
        ),
    ]
