# Generated by Django 3.1.4 on 2020-12-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20201217_0507"),
        ("patients", "0004_auto_20201217_0507"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.agencyprofile",
            ),
            preserve_default=False,
        ),
    ]
