# Generated by Django 3.1.4 on 2020-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patient_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="zip",
            field=models.CharField(max_length=5),
        ),
    ]
