# Generated by Django 3.1.4 on 2020-12-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_auto_20201218_1859"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrequest",
            name="gender",
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Female"), (2, "Male"), (3, "Other")], default=1
            ),
            preserve_default=False,
        ),
    ]
