# Generated by Django 3.1.4 on 2021-01-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_auto_20201221_0338"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicerequested",
            options={"verbose_name_plural": "Service Requests"},
        ),
    ]
