# Generated by Django 3.1.4 on 2021-01-19 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_auto_20210115_1615"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestnotes",
            options={"verbose_name_plural": "Request notes"},
        ),
        migrations.AddField(
            model_name="patientrequest",
            name="frequency",
            field=models.IntegerField(
                choices=[(1, "Per Week"), (2, "Per Month")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientrequest",
            name="hours",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientrequest",
            name="requested_schedule",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
