# Generated by Django 3.1.4 on 2021-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_auto_20210119_0129"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
