# Generated by Django 3.1.4 on 2021-01-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0012_patientrequest_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrequest",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
