# Generated by Django 3.1.4 on 2021-01-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0014_auto_20210121_0255"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="phone",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
    ]
