# Generated by Django 3.1.4 on 2021-01-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0016_auto_20210125_0635"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrequest",
            name="status",
        ),
        migrations.AddField(
            model_name="servicerequested",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Open"), (2, "Pending"), (3, "Closed")], default=1
            ),
        ),
    ]
