# Generated by Django 3.1.5 on 2021-02-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0018_merge_20210205_0014"),
        ("patients", "0018_merge_20210128_0115"),
    ]

    operations = []
