# Generated by Django 3.1.5 on 2021-02-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_is_verified"),
        ("patients", "0019_merge_20210209_0152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequested",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_services",
                to="users.ProviderProfile",
            ),
        ),
    ]
