# Generated by Django 3.1.5 on 2021-02-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0020_auto_20210209_0203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrequest",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="patientrequest",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="patientrequest",
            name="requested_schedule",
        ),
    ]
