# Generated by Django 3.1.5 on 2021-02-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0021_auto_20210209_2212"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequested",
            name="requested_schedule",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
