# Generated by Django 3.1.5 on 2021-02-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0022_servicerequested_requested_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequested",
            name="hours",
            field=models.PositiveIntegerField(),
        ),
    ]
