# Generated by Django 3.1.5 on 2021-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0023_auto_20210212_1950"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableColumns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("sequence", models.IntegerField()),
                (
                    "role",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Provider"), (2, "Agency")],
                        null=True,
                    ),
                ),
                (
                    "table_name",
                    models.IntegerField(
                        choices=[(1, "Patient Requests")], default=1
                    ),
                ),
                (
                    "sort_label",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "column_types",
                    models.IntegerField(
                        choices=[(1, "Default"), (2, "Custom")], default=1
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
