# Generated by Django 3.1.5 on 2021-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0024_tablecolumns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tablecolumns",
            options={"verbose_name_plural": "Table Columns"},
        ),
        migrations.RenameField(
            model_name="tablecolumns",
            old_name="column_types",
            new_name="column_type",
        ),
    ]
