# Generated by Django 3.1.5 on 2021-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_requestnotes_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed')], default=1),
        ),
    ]
