# Generated by Django 3.1.5 on 2021-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0031_auto_20210326_0843"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequested",
            name="requested_schedule",
        ),
        migrations.AddField(
            model_name="patientrequest",
            name="requested_schedule",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
