# Generated by Django 3.1.5 on 2021-06-16 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210216_1743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_auto_20210616_1014'),
        ('patients', '0033_historicalpatient_historicalpatientrequest_historicalservicerequested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.agencyprofile'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='patient',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='requestnotes',
            name='account',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account'),
        ),
        migrations.AlterField(
            model_name='requestnotes',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestnotes',
            name='request',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patientrequest'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='funding_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.fundingsource'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='interests',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='interested_services', to='users.ProviderProfile'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='match',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_match', to='users.providerprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='request',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patientrequest'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='services.servicetype'),
        ),
    ]
