# Generated by Django 3.1.5 on 2021-08-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_historicalrequestnotes_history_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientrequest',
            name='is_archived',
            field=models.IntegerField(choices=[(0, 'Not_ARCHIVED'), (1, 'ARCHIVED')], default=0),
        ),
        migrations.AddField(
            model_name='patientrequest',
                name='is_archived',
            field=models.IntegerField(choices=[(0, 'Not_ARCHIVED'), (1, 'ARCHIVED')], default=0),
        ),
    ]
