# Generated by Django 3.1.5 on 2021-08-18 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0038_archivedpatientrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDeletePatientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.IntegerField(choices=[(1, 'Client deceased.'), (2, 'Client circumstances changed.'), (3, 'Client has moved to new agency.'), (4, 'Request fulfilled outside of Duett.'), (5, 'Other (tell us why).')], default=1)),
                ('is_type', models.IntegerField(choices=[(0, 'ARCHIVED'), (1, 'DELETED')], default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='historicalpatientrequest',
            name='is_archived',
            field=models.IntegerField(choices=[(0, 'NOT_ARCHIVED'), (1, 'ARCHIVED')], default=0),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='is_archived',
            field=models.IntegerField(choices=[(0, 'NOT_ARCHIVED'), (1, 'ARCHIVED')], default=0),
        ),
        migrations.DeleteModel(
            name='ArchivedPatientRequest',
        ),
        migrations.AddField(
            model_name='archiveddeletepatientrequest',
            name='request',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patientrequest'),
        ),
    ]
