# Generated by Django 3.1.5 on 2021-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_auto_20210818_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
