# Generated by Django 3.1.5 on 2021-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_auto_20210819_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddeletepatientrequest',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Client information entered incorrectly'), (2, 'Care plan/request entered incorrectly')], default=1),
        ),
    ]
