# Generated by Django 3.1.5 on 2021-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_auto_20210902_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_title', models.CharField(blank=True, max_length=300, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 1)], default=0)),
                ('parameter', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),        
    ]
