# Generated by Django 3.2.8 on 2021-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0043_auto_20210929_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicerequested',
            name='is_delete',
            field=models.IntegerField(choices=[(0, 'NOT_DELETE'), (1, 'DELETED')], default=0),
        ),
        migrations.AddField(
            model_name='historicalservicerequested',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalservicerequested',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Other (tell us why).'), (2, 'Client information entered incorrectly'), (3, 'Care plan/request entered incorrectly')], default=1),
        ),
        migrations.AddField(
            model_name='servicerequested',
            name='is_delete',
            field=models.IntegerField(choices=[(0, 'NOT_DELETE'), (1, 'DELETED')], default=0),
        ),
        migrations.AddField(
            model_name='servicerequested',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequested',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Other (tell us why).'), (2, 'Client information entered incorrectly'), (3, 'Care plan/request entered incorrectly')], default=1),
        ),
    ]
