# Generated by Django 3.2.8 on 2021-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_patientactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed'), (4, 'Partially Matched')], default=1),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed'), (4, 'Partially Matched')], default=1),
        ),
    ]
