# Generated by Django 3.2.8 on 2021-11-30 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210216_1743'),
        ('patients', '0046_auto_20211022_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequested',
            name='funding_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funding_source', to='services.fundingsource'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='request',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_request', to='patients.patientrequest'),
        ),
        migrations.AlterField(
            model_name='servicerequested',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_type', to='services.servicetype'),
        ),
    ]
