# Generated by Django 3.2.8 on 2021-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_auto_20211022_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicerequested',
            name='match_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequested',
            name='match_date',
            field=models.DateField(null=True),
        ),
    ]
