# Generated by Django 3.2.8 on 2021-12-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0048_alter_servicerequested_request'),
        ('patients', '0048_auto_20211127_1224'),
    ]

    operations = [
    ]
