# Generated by Django 3.2.8 on 2023-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0051_auto_20230313_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientrequest',
            name='initial_created_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatientrequest',
            name='refreshed_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='initial_created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='refreshed_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
