# Generated by Django 3.2.8 on 2023-03-15 12:57

from django.db import migrations
from django.db.models import F


def copy_created_at_to_initial_and_refreshed_time(apps, schema_editor):
    MyModel = apps.get_model('patients', 'PatientRequest')
    MyModel.objects.all().update(refreshed_time=F('created_at'))
    MyModel.objects.all().update(initial_created_time=F('created_at'))


class Migration(migrations.Migration):
    dependencies = [
        ('patients', '0052_auto_20230315_1235'),
    ]

    operations = [migrations.RunPython(code=copy_created_at_to_initial_and_refreshed_time), ]
