# Generated by Django 3.2.8 on 2023-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0053_auto_20230315_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='refreshed_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
